{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from OCC.Core.STEPControl import STEPControl_Reader\n",
    "from OCC.Core.IFSelect import IFSelect_RetDone\n",
    "from OCC.Core.BRepGProp import brepgprop_VolumeProperties\n",
    "from OCC.Core.GProp import GProp_GProps\n",
    "from OCC.Core.STEPControl import STEPControl_Reader\n",
    "from OCC.Core.IFSelect import IFSelect_RetDone\n",
    "from OCC.Display.WebGl.jupyter_renderer import JupyterRenderer\n",
    "from OCC.Core.gp import gp_Vec, gp_Pnt, gp_Trsf\n",
    "from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_Transform\n",
    "import sys\n",
    "import numpy as np\n",
    "from copy import deepcopy\n",
    "import ipywidgets as widgets\n",
    "\n",
    "def load_step_file(filename):\n",
    "    \"\"\"Load a STEP file and return the shape.\"\"\"\n",
    "    step_reader = STEPControl_Reader()\n",
    "    status = step_reader.ReadFile(filename)\n",
    "    if status != IFSelect_RetDone:\n",
    "        raise Exception(\"Error: Cannot read STEP file.\")\n",
    "    # Transfer the roots and get the shape\n",
    "    step_reader.TransferRoots()\n",
    "    shape = step_reader.OneShape()\n",
    "    return shape\n",
    "\n",
    "def compute_mass_properties(shape):\n",
    "    \"\"\"Compute mass properties such as volume (interpreted as mass for unit density)\n",
    "    and the center of mass of the given shape.\"\"\"\n",
    "    props = GProp_GProps()\n",
    "    brepgprop_VolumeProperties(shape, props)\n",
    "    mass = props.Mass()  # For solids, this gives the volume (mass = volume * density)\n",
    "    center_of_mass = props.CentreOfMass()\n",
    "    matrix_of_inertia = props.MatrixOfInertia()\n",
    "    matrix_of_inertia = np.array([[matrix_of_inertia.Value(1, 1), matrix_of_inertia.Value(1, 2), matrix_of_inertia.Value(1, 3)],\n",
    "                                  [matrix_of_inertia.Value(2, 1), matrix_of_inertia.Value(2, 2), matrix_of_inertia.Value(2, 3)],\n",
    "                                  [matrix_of_inertia.Value(3, 1), matrix_of_inertia.Value(3, 2), matrix_of_inertia.Value(3, 3)]])\n",
    "    return mass, center_of_mass, matrix_of_inertia\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "shape_1 = load_step_file(\"examples/pentagonextrude.step\")\n",
    "shape_2 = load_step_file(\"examples/hexextrude.step\")\n",
    "\n",
    "shape_1_copy = deepcopy(shape_1)\n",
    "shape_2_copy = deepcopy(shape_2)\n",
    "\n",
    "m1, c1, mat1 = compute_mass_properties(shape_1)\n",
    "m2, c2, mat2 = compute_mass_properties(shape_2)\n",
    "\n",
    "eig1, v1 = np.linalg.eigh(mat1)\n",
    "eig2, v2 = np.linalg.eigh(mat2)\n",
    "\n",
    "s1 = np.sqrt(np.abs(eig1).sum()/m1)\n",
    "s2 = np.sqrt(np.abs(eig2).sum()/m2)\n",
    "\n",
    "translation_vector = gp_Vec(-c1.X(), -c1.Y(), -c1.Z())\n",
    "translation = gp_Trsf()\n",
    "translation.SetTranslation(translation_vector)\n",
    "# translation.SetScale(gp_Pnt(0,0,0),1/s1)\n",
    "shape_1 = BRepBuilderAPI_Transform(shape_1, translation, True).Shape()\n",
    "\n",
    "scaling = gp_Trsf()\n",
    "scaling.SetScale(gp_Pnt(0,0,0), 1/s1)\n",
    "shape_1 = BRepBuilderAPI_Transform(shape_1, scaling, True).Shape()\n",
    "\n",
    "translation_vector = gp_Vec(-c2.X(), -c2.Y(), -c2.Z())\n",
    "translation = gp_Trsf()\n",
    "translation.SetTranslation(translation_vector)\n",
    "# translation.SetScale(gp_Pnt(0,0,0),1/s2)\n",
    "shape_2 = BRepBuilderAPI_Transform(shape_2, translation, True).Shape()\n",
    "scaling = gp_Trsf()\n",
    "scaling.SetScale(gp_Pnt(0,0,0), 1/s2)\n",
    "shape_2 = BRepBuilderAPI_Transform(shape_2, scaling, True).Shape()\n",
    "\n",
    "# rotation to align 2 on 1\n",
    "R = v1 @ v2.T\n",
    "rotation = gp_Trsf()\n",
    "rotation.SetValues(R[0,0], R[0,1], R[0,2], 0,\n",
    "                    R[1,0], R[1,1], R[1,2], 0,\n",
    "                    R[2,0], R[2,1], R[2,2], 0)\n",
    "shape_2 = BRepBuilderAPI_Transform(shape_2, rotation, True).Shape()\n",
    "\n",
    "# Initialize the Jupyter renderer\n",
    "display = JupyterRenderer()\n",
    "\n",
    "# Display the shape interactively in the notebook cell\n",
    "display.DisplayShape(shape_1)\n",
    "display.DisplayShape(shape_2, shape_color='red')\n",
    "\n",
    "\n",
    "display_og = JupyterRenderer()\n",
    "display_og.DisplayShape(shape_1_copy)\n",
    "display_og.DisplayShape(shape_2_copy, shape_color='red')\n",
    "\n",
    "\n",
    "widgets.VBox([display_og.Display(), display.Display()])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "spatial",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
